[package]
name = "preprocess_cancellation"
version = "0.1.0"
edition = "2021"

[lib]
name = "preprocess_cancellation"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.79"
pyo3 = "0.19.0"
tempfile = "3.9.0"
winnow = "0.5.34"
